#!/usr/bin/env bash

BOTTOM=$(grep BOTTOM .env | cut -d '=' -f2 | cut -d '#' -f1)
echo

if [ $BOTTOM = "host" ]; then
  export APP_PATH=$PWD
elif [ $BOTTOM = "machine" ]; then
  export APP_PATH=${PWD/home/hosthome}
fi

docker-compose -f docker-compose.yml build app
docker-compose \
  -f docker-compose.yml \
  down
docker-compose \
  -f docker-compose.yml \
  up #-d
# docker container attach app
